# try builds on mac
osx_image: xcode61

language: java

node_js:
  - 0.10

jdk: oraclejdk7

# whitelist
# branches:
#   only:
#     - travis

# notifications:
#   email:
#     recipients:
#       - lingsync-support@googlegroups.com
#     on_success: change
#     on_failure: always

env:
  matrix:
    # see set_up_new_machine.sh

before_install:
  # Download and configure android among other deps
  - ./scripts/set_up_new_machine.sh

before_script:
  # Make sure the emulator has started before running tests
  - ./scripts/wait_for_emulator.sh

  # Travis supports running a real browser (Firefox) with a virtual screen. Just update your .travis.yml to set up the virtual screen like this:
  # Use a dsiplay so sikuli can have  a screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: npm test
